// Sample data for ITS modules - JavaScript Events and Event Handling
import { Module, PretestQuestion } from './types';

export const sampleModules: Module[] = [
  {
    id: 1,
    title: 'Module 1: Events in JavaScript',
    description: 'Learn what events are and how they work in JavaScript',
    icon: '⚡',
    sections: [
      {
        id: 1,
        title: 'Pretest',
        description: 'Assess your current knowledge',
        isLocked: false,
        progress: 0,
        pretestRequired: true,
        content: 'pretest',
      },
      {
        id: 2,
        title: 'Events - Conceptual',
        description: 'Define what an event is and understand event concepts',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'events-conceptual',
      },
      {
        id: 3,
        title: 'Click Events - Procedural',
        description: 'Write a click event with proper syntax',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'click-events-procedural',
      },
      {
        id: 4,
        title: 'Event Types',
        description: 'Identify different types of events (Click, Hover, etc.)',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'event-types',
      },
      {
        id: 5,
        title: 'Events & User Input',
        description: 'Understand how events respond to user input',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'events-user-input',
      },
      {
        id: 6,
        title: 'Events & DOM Changes',
        description: 'Explore how events trigger changes in the DOM',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'events-dom-changes',
      },
      {
        id: 7,
        title: 'Project: Event Explorer',
        description: 'Create interactive elements that respond to events',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'project-event-explorer',
      },
      {
        id: 8,
        title: 'Posttest',
        description: 'Assess what you learned about events',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'posttest',
      },
    ],
    overallProgress: 0,
    isStarted: false,
  },
  {
    id: 2,
    title: 'Module 2: Event Handlers',
    description: 'Master event handlers and how to execute code on events',
    icon: '🎯',
    sections: [
      {
        id: 9,
        title: 'Pretest',
        description: 'Assess your current knowledge',
        isLocked: false,
        progress: 0,
        pretestRequired: true,
        content: 'pretest',
      },
      {
        id: 10,
        title: 'Event Handlers - Definition',
        description: 'Define what an event handler is',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'handler-definition',
      },
      {
        id: 11,
        title: 'Handler Firing',
        description: 'Understand when and why handlers fire',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'handler-firing',
      },
      {
        id: 12,
        title: 'Writing Event Handlers',
        description: 'Write functions for event handlers',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'write-handlers',
      },
      {
        id: 13,
        title: 'Handler Behavior Differences',
        description: 'Understand different handlers do different things',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'handler-differences',
      },
      {
        id: 14,
        title: 'Project: Multiple Handlers',
        description: 'Implement multiple handlers for different purposes',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'project-multiple-handlers',
      },
      {
        id: 15,
        title: 'Posttest',
        description: 'Assess what you learned about event handlers',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'posttest',
      },
    ],
    overallProgress: 0,
    isStarted: false,
  },
  {
    id: 3,
    title: 'Module 3: Event Target & Buttons',
    description: 'Learn about event targets, buttons, and element selection',
    icon: '🖱️',
    sections: [
      {
        id: 16,
        title: 'Pretest',
        description: 'Assess your current knowledge',
        isLocked: false,
        progress: 0,
        pretestRequired: true,
        content: 'pretest',
      },
      {
        id: 17,
        title: 'Target - Definition',
        description: 'Define what a target is in event context',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'target-definition',
      },
      {
        id: 18,
        title: 'Accessing Target',
        description: 'Learn how to access event.target in handlers',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'accessing-target',
      },
      {
        id: 19,
        title: 'Differentiating Targets',
        description: 'Differentiate between different target elements',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'differentiating-targets',
      },
      {
        id: 20,
        title: 'Using event.target - Procedural',
        description: 'Write code using event.target in handlers',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'using-event-target',
      },
      {
        id: 21,
        title: 'Button Fundamentals',
        description: 'Understand button elements and their properties',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'button-fundamentals',
      },
      {
        id: 22,
        title: 'Button Events & Syntax',
        description: 'Write buttons with proper syntax and event attributes',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'button-events-syntax',
      },
      {
        id: 23,
        title: 'Multiple Handlers & Targets',
        description: 'Use one handler for multiple elements via targets',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'multiple-handlers-targets',
      },
      {
        id: 24,
        title: 'Project: Button Controller',
        description: 'Create buttons that control different actions',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'project-button-controller',
      },
      {
        id: 25,
        title: 'Posttest',
        description: 'Assess what you learned about targets and buttons',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'posttest',
      },
    ],
    overallProgress: 0,
    isStarted: false,
  },
  {
    id: 4,
    title: 'Module 4: Event Listeners',
    description: 'Master addEventListener and event listener patterns',
    icon: '👂',
    sections: [
      {
        id: 26,
        title: 'Pretest',
        description: 'Assess your current knowledge',
        isLocked: false,
        progress: 0,
        pretestRequired: true,
        content: 'pretest',
      },
      {
        id: 27,
        title: 'Listener Definition',
        description: 'Define what an event listener is',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'listener-definition',
      },
      {
        id: 28,
        title: 'Writing Event Listeners',
        description: 'Write event listeners with addEventListener',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'write-listeners',
      },
      {
        id: 29,
        title: 'Listener Functionality',
        description: 'Understand what event listeners do',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'listener-functionality',
      },
      {
        id: 30,
        title: 'Multiple Listeners',
        description: 'Use multiple listeners on the same event',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'multiple-listeners',
      },
      {
        id: 31,
        title: 'Listener vs Handler',
        description: 'Understand the difference between listeners and handlers',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'listener-vs-handler',
      },
      {
        id: 32,
        title: 'addEventListener vs onclick',
        description: 'Learn the differences between addEventListener and onclick',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'addlistener-vs-onclick',
      },
      {
        id: 33,
        title: 'Project: Advanced Event System',
        description: 'Build a complex event system with multiple listeners',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'project-advanced-events',
      },
      {
        id: 34,
        title: 'Posttest',
        description: 'Assess what you learned about event listeners',
        isLocked: true,
        progress: 0,
        pretestRequired: false,
        content: 'posttest',
      },
    ],
    overallProgress: 0,
    isStarted: false,
  },
];

export const samplePretestQuestions: PretestQuestion[] = [
  {
    id: 1,
    question: 'What is an event in JavaScript?',
    options: [
      'A function that runs on a schedule',
      'Something that happens in response to user interaction or system action',
      'A variable that stores a value',
      'A method to style HTML elements',
    ],
    correctAnswer: 1,
  },
  {
    id: 2,
    question: 'Which of the following is a valid event type?',
    options: [
      'execute',
      'respond',
      'click',
      'activate',
    ],
    correctAnswer: 2,
  },
  {
    id: 3,
    question: 'What does an event handler do?',
    options: [
      'Stores event data permanently',
      'Executes code when an event is triggered',
      'Prevents events from happening',
      'Creates new events',
    ],
    correctAnswer: 1,
  },
  {
    id: 4,
    question: 'How do you access the element that triggered an event?',
    options: [
      'event.element',
      'event.source',
      'event.target',
      'event.origin',
    ],
    correctAnswer: 2,
  },
  {
    id: 5,
    question: 'What is the difference between addEventListener and onclick?',
    options: [
      'They do the same thing',
      'onclick can only have one listener; addEventListener allows multiple',
      'addEventListener is older',
      'onclick only works on buttons',
    ],
    correctAnswer: 1,
  },
];
